(in-package :utaticl.core)

(defmethod render-body ((self editor-automation))
)

(defmethod render-header ((self editor-automation))
  (let* ((clip (.clip self))
         (lane (.lane clip))
         (param (.automation-param lane))
         (text-min (value-text param 0d0))
         (text-half (value-text param .5d0))
         (text-max (value-text param 1d0))
         (text-half-size (ig:calc-text-size text-half))
         (text-max-size (ig:calc-text-size text-max))
         (pos-min (@ (+ (.offset-x self) 4.0) .0))
         (scrollbar-size (plus-c:c-ref (ig:get-style) ig:im-gui-style :scrollbar-size))
         (pos-half (@ (+ (.offset-x self)
                         (/ (- (ig:get-window-width)
                               (.offset-x self)
                               scrollbar-size)
                            2)
                         (- (/ (.x text-half-size) 2))
                         -4.0)
                      .0))
         (pos-max (@ (- (ig:get-window-width)
                        scrollbar-size
                        (.x text-max-size)
                        4.0)
                     .0)))
    (ig:set-cursor-pos pos-min)
    (ig:text text-min)
    (ig:set-cursor-pos pos-half)
    (ig:text text-half)
    (ig:set-cursor-pos pos-max)
    (ig:text text-max)))

