(in-package :utaticl.core)

(defmethod render ((self midi-device-window))
  (ig:with-begin ("Midi Device Config")
    (when (ig:is-window-appearing)
      (ig:set-window-focus)
      (setf (.midi-devices-in self) (midi-devices-in))
      (setf (.midi-devices-out self) (midi-devices-out)))
    (ig:text "Input")
    (loop for device-name in (.midi-devices-in self)
          do (let ((checked (member device-name (.midi-devices-in *config*) :test #'equal)))
               (when (ig:checkbox device-name checked)
                 (if checked
                     (progn
                       (push device-name (.midi-devices-in *config*))
                       (open-midi-device-in device-name)
                       )
                     (progn
                       (setf (.midi-devices-in *config*)
                             (remove device-name (.midi-devices-in *config*) :test #'equal))
                       (setf (.midi-devices-in *app*)
                             (loop for device in (.midi-devices-in *app*)
                                   if (equal device-name (.name device))
                                     do (close-midi-device-in device)
                                   else
                                     collect device))))
                 (config-save *config*))))
    (ig:separator)
    (when (ig:button "Close")
      (hide self))))
