(in-package :utaticl.core)

(defmethod process ((self module-builtin))
  (when (and (plusp (length (.inputs *process-data*)))
             (plusp (length (.outputs *process-data*))))
    (loop with input-channel0 = (buffer-at (car (.inputs *process-data*)) 0)
          with input-channel1 = (buffer-at (car (.inputs *process-data*)) 1)
          with output-channel0 = (buffer-at (car (.outputs *process-data*)) 0)
          with output-channel1 = (buffer-at (car (.outputs *process-data*)) 1)
          with input-channel0-const-p = (const-get (car (.inputs *process-data*)) 0)
          with input-channel1-const-p = (const-get (car (.inputs *process-data*)) 1)
          for i below (.frames-per-buffer *config*)
          do (setf (values (cffi:mem-aref output-channel0 :float i)
                           (cffi:mem-aref output-channel1 :float i))
                   (process-sample self
                                   (cffi:mem-aref input-channel0 :float i)
                                   (cffi:mem-aref input-channel1 :float i))))
    (const-set (car (.outputs *process-data*)) 0 nil)
    (const-set (car (.outputs *process-data*)) 1 nil)
    #+nil
    (loop for channel-index below 2
          for input-channel = (buffer-at (car (.inputs *process-data*)) channel-index)
          for output-channel = (buffer-at (car (.outputs *process-data*)) channel-index)
          for input-const-p = (const-get (car (.inputs *process-data*)) channel-index)
          do (loop for i below (.frames-per-buffer *config*)
                   do (setf (cffi:mem-aref output-channel :float i)
                            (process-sample self (cffi:mem-aref input-channel :float i))))
             (const-set (car (.outputs *process-data*)) channel-index nil)))
  (call-next-method))

(defmethod state ((self module-builtin))
  (let ((state nil))
    (maphash (lambda (key value)
               (push (list key (.value value)) state))
             (.params self))
    state))

(defmethod (setf state) (state (self module-builtin))
  (loop for (id value) in state
        do (setf (.value (param self id)) value)))
